---
language: node_js
sudo: false
node_js:
- '8'
- '9'
env:
  global:
  - SAUCE_USERNAME=sc-launcher-ci
  - SAUCE_ACCESS_KEY=9f0d1fc0-df51-4863-9761-7879fa9ff844
  - SAUCE_API_HOST=eu-central-1.saucelabs.com
  - VERBOSE_TESTS=1
script:
  - npm run lint
  - npm test
