---
language: node_js
sudo: false
node_js:
- '6'
- '7'
env:
  global:
  - SAUCE_USERNAME=sc-launcher-ci
  - SAUCE_ACCESS_KEY=9f0d1fc0-df51-4863-9761-7879fa9ff844
  - VERBOSE_TESTS=1
script:
  - npm run lint
  - npm test
